# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sPbcL4RAesIIBIfpbYQN1DeMGgUTg85k
"""

from object_detection import detect_common_objects